--- #YAML:1.0
name:               Bio-KEGGI
version:            v0.1.2
abstract:           Module to handle KEGG genome, ko and pathway files
author:
    - Haizhou Liu <zeroliu@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Switch:      0
    Test::More:  0
    Text::Trim:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
